name: Discord PR Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Send notification to Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d "{\"content\": \"Pull request opened by ${{ github.actor }}: ${{ github.event.pull_request.html_url }}\"}" \
        ${DISCORD_WEBHOOK_URL}
